version: '3.8'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mynetwork
    
    
networks:
  mynetwork:
    external:
      name: shopping_list